project_id = "perfpsiibarwgvjtrlxr"

[functions.send-invite]
verify_jwt = true

[functions.extract-linkedin]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.complete-profile]
verify_jwt = false

[functions.sync-helloasso]
verify_jwt = true

[functions.sync-helloasso-members]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.process-transcript]
verify_jwt = false

[functions.scrape-associations]
verify_jwt = false
